// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtA_TI_IkeMm6KbZrraz6dcaux4_MT1a8',
    appId: '1:470120917570:web:3e3581865bca3294b61bdb',
    messagingSenderId: '470120917570',
    projectId: 'flexihome-1ccf6',
    authDomain: 'flexihome-1ccf6.firebaseapp.com',
    storageBucket: 'flexihome-1ccf6.firebasestorage.app',
    measurementId: 'G-1HV53V7QZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtYWxaZQANgQgO9Bib4qJltcSf0JORmpA',
    appId: '1:470120917570:android:7d64919356247482b61bdb',
    messagingSenderId: '470120917570',
    projectId: 'flexihome-1ccf6',
    storageBucket: 'flexihome-1ccf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW3GqLT4B2um9SX423L8AhQnya_WnhbTw',
    appId: '1:470120917570:ios:286fe87a0b5e6f24b61bdb',
    messagingSenderId: '470120917570',
    projectId: 'flexihome-1ccf6',
    storageBucket: 'flexihome-1ccf6.firebasestorage.app',
    iosBundleId: 'com.codifypro.flexihome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtA_TI_IkeMm6KbZrraz6dcaux4_MT1a8',
    appId: '1:470120917570:web:9453a58a840e3af9b61bdb',
    messagingSenderId: '470120917570',
    projectId: 'flexihome-1ccf6',
    authDomain: 'flexihome-1ccf6.firebaseapp.com',
    storageBucket: 'flexihome-1ccf6.firebasestorage.app',
    measurementId: 'G-03KMFKVVW9',
  );

}